### PR TITLE
:art: whitespace

### PR DESCRIPTION
**Pull request by miketheman**
- W291 trailing whitespace
- W293 blank line contains whitespace

Signed-off-by: Mike Fiedler <miketheman@gmail.com>

### CODE REVIEW

**Comment by miketheman** [comment]
First commit to start resolving #41 - resolves all `W` warnings.

Compare with this link to see all whitespace removed: https://github.com/jterrace/sphinxtr/pull/42/files?w=1
Confirms no changes other than whitespace.

**Comment by miketheman** [comment]
The build failure appears to be a problem in the parameters being passed to `inline_all_toctrees`.
This changed circa Sphinx 1.3.2 in https://github.com/sphinx-doc/sphinx/commit/49b812b856f3c81c6edee5ba793405c7ed927cf3

This project appears to not have been built successfully since Sphinx 1.2.3 a year ago - is this something that should be pinned/addressed before or after this commit?

**Comment by jterrace** [comment]
Thanks!

**Comment by jterrace** [comment]
I fixed the "make singletext" failure, as it was a simple fix. Now "make latex" is failing and it looks like a harder issue to debug. I'm afraid I don't have much time right now to figure out, but I'd be happy to review a pull request with a fix. Sorry for the broken build!

**Comment by miketheman** [comment]
@jterrace Cool.

The latex error appears to surface from this refactor change: https://github.com/sphinx-doc/sphinx/commit/279ac7c23fe2f35025514d64c96f839bd518c786

**Pull request merged**
